"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.generationRouter = void 0;
const express_1 = require("express");
const generation_controller_js_1 = require("./generation.controller.js");
const auth_middleware_js_1 = require("../auth/auth.middleware.js");
const router = (0, express_1.Router)();
router.use(auth_middleware_js_1.authenticateJWT);
router.get('/', generation_controller_js_1.generationController.listGenerations.bind(generation_controller_js_1.generationController));
router.get('/:id', generation_controller_js_1.generationController.getGeneration.bind(generation_controller_js_1.generationController));
router.get('/:id/content', generation_controller_js_1.generationController.getGenerationContent.bind(generation_controller_js_1.generationController));
exports.generationRouter = router;
