"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.repositoryRouter = void 0;
const express_1 = require("express");
const repository_controller_js_1 = require("./repository.controller.js");
const auth_middleware_js_1 = require("../auth/auth.middleware.js");
const router = (0, express_1.Router)();
router.use(auth_middleware_js_1.authenticateJWT);
router.post('/', repository_controller_js_1.repositoryController.add);
router.get('/', repository_controller_js_1.repositoryController.list);
router.patch('/:id/active', repository_controller_js_1.repositoryController.toggleActive);
exports.repositoryRouter = router;
