"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.contentRouter = void 0;
const express_1 = require("express");
const content_controller_js_1 = require("./content.controller.js");
const auth_middleware_js_1 = require("../auth/auth.middleware.js");
const router = (0, express_1.Router)();
router.use(auth_middleware_js_1.authenticateJWT);
router.post('/:id/approve', content_controller_js_1.contentController.approveContent.bind(content_controller_js_1.contentController));
router.post('/:id/reject', content_controller_js_1.contentController.rejectContent.bind(content_controller_js_1.contentController));
exports.contentRouter = router;
