"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.dashboardRouter = void 0;
const express_1 = require("express");
const dashboard_controller_js_1 = require("./dashboard.controller.js");
const auth_middleware_js_1 = require("../auth/auth.middleware.js");
const router = (0, express_1.Router)();
router.use(auth_middleware_js_1.authenticateJWT);
router.get('/', dashboard_controller_js_1.dashboardController.getDashboardStats.bind(dashboard_controller_js_1.dashboardController));
exports.dashboardRouter = router;
